---
title: "Serdar Balci, MD, Pathologist"
site: distill::distill_website
listing: posts
---

::: {itemscope="" itemtype="https://schema.org/Person"}
```{=html}
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Person",
  "name": "Serdar Balcı",
  "url": "https://www.serdarbalci.com/",
  "jobTitle": "MD, Pathologist",
  "sameAs": [
    "https://www.facebook.com/serdarbalcimd",
    "https://www.facebook.com/serdarbalcimdpathologist/",
    "https://www.instagram.com/balciserdar/",
    "https://www.linkedin.com/in/serdar-balci-md-pathologist/",
    "https://twitter.com/serdarbalci",
    "https://github.com/sbalci",
    "https://www.parapathology.com",
    "https://www.patolojinotlari.com",
    "https://www.patolojiai.com/",
    "https://www.memorial.com.tr/doktorlar/serdar-balci"
  ]
}
</script>
```
:::

<br><br>

+--------+---------+-----------------+----+-----------------+-------+
| R-p    | jamovi  | Pathology       | Im | Genes           | Pages |
| roject |         |                 | ag |                 |       |
|        |         |                 | es |                 |       |
+========+=========+=================+====+=================+=======+
| [      | [issues | [WHO Blue       | [  | [cBioPorta      | [     |
| MyRCod | ](https | Books](https:   | Qu | l](http://www.c | patol |
| es](ht | ://gith | //tumourclassif | Pa | bioportal.org/) | ojiAI |
| tps:// | ub.com/ | ication.iarc.wh | th |                 | ](htt |
| github | jamovi/ | o.int/welcome/) | ]( |                 | ps:// |
| .com/s | jamovi/ |                 | ht |                 | www.p |
| balci/ | issues) |                 | tp |                 | atolo |
| MyRCod |         |                 | s: |                 | jiai. |
| esForD |         |                 | // |                 | com/) |
| ataAna |         |                 | qu |                 |       |
| lysis) |         |                 | pa |                 |       |
|        |         |                 | th |                 |       |
|        |         |                 | .g |                 |       |
|        |         |                 | it |                 |       |
|        |         |                 | hu |                 |       |
|        |         |                 | b. |                 |       |
|        |         |                 | io |                 |       |
|        |         |                 | /) |                 |       |
+--------+---------+-----------------+----+-----------------+-------+
| [R-bl  | [relea  | [CAP Cancer     | [  | [Coursera       | [droz |
| oggers | ses](ht | Protocol](http  | Im | ](https://www.c | lemba |
| ](http | tps://w | s://www.cap.org | ag | oursera.org/lea | lci]( |
| s://ww | ww.jamo | /protocols-and- | eJ | rn/data-genes-m | https |
| w.r-bl | vi.org/ | guidelines/canc | ]( | edicine/lecture | ://ww |
| oggers | downloa | er-reporting-to | ht | /uVUus/working- | w.dro |
| .com/) | d.html) | ols/cancer-prot | tp | with-cbioportal | zlemb |
|        |         | ocol-templates) | s: | -gene-networks) | alci. |
|        |         |                 | // |                 | com/) |
|        |         |                 | im |                 |       |
|        |         |                 | ag |                 |       |
|        |         |                 | ej |                 |       |
|        |         |                 | .g |                 |       |
|        |         |                 | it |                 |       |
|        |         |                 | hu |                 |       |
|        |         |                 | b. |                 |       |
|        |         |                 | io |                 |       |
|        |         |                 | /) |                 |       |
+--------+---------+-----------------+----+-----------------+-------+
| [R     | [forum  |                 |    |                 | [     |
| -weekl | ](https |                 |    |                 | patol |
| y](htt | ://foru |                 |    |                 | ojino |
| ps://r | m.jamov |                 |    |                 | tlari |
| weekly | i.org/) |                 |    |                 | ](htt |
| .org/) |         |                 |    |                 | ps:// |
|        |         |                 |    |                 | www.p |
|        |         |                 |    |                 | atolo |
|        |         |                 |    |                 | jinot |
|        |         |                 |    |                 | lari. |
|        |         |                 |    |                 | com/) |
+--------+---------+-----------------+----+-----------------+-------+
|        | [de     |                 |    |                 | [p    |
|        | v](http |                 |    |                 | arapa |
|        | s://dev |                 |    |                 | tholo |
|        | .jamovi |                 |    |                 | gy](h |
|        | .org/tu |                 |    |                 | ttps: |
|        | ts0101- |                 |    |                 | //www |
|        | getting |                 |    |                 | .para |
|        | -starte |                 |    |                 | patho |
|        | d.html) |                 |    |                 | logy. |
|        |         |                 |    |                 | com/) |
+--------+---------+-----------------+----+-----------------+-------+
|        | [Cli    |                 |    |                 | [PBP  |
|        | nicoPat |                 |    |                 | ath]( |
|        | h](http |                 |    |                 | https |
|        | s://www |                 |    |                 | ://pb |
|        | .serdar |                 |    |                 | path. |
|        | balci.c |                 |    |                 | org/) |
|        | om/Clin |                 |    |                 |       |
|        | icoPath |                 |    |                 |       |
|        | JamoviM |                 |    |                 |       |
|        | odule/) |                 |    |                 |       |
+--------+---------+-----------------+----+-----------------+-------+

: For My Daily Visits

<br>

<hr>
