---
title: "Patolojide Bilişim"
description: |
  Bu yazı *Prof. Dr. Alp Usubütün* editörlüğünde hazırlanan *"Sağlık Bilimleri İçin Patoloji ve Patoloji Laboratuvarını Anlama Kılavuzu 2. Baskı - Ekim 2022 Ankara Nobel Tıp Kitabevleri ISBN: 978-625-7564-70-0"* adlı kitaptaki *"8. Bölüm: Patolojide Yeni Yöntemler ve Gelecek"* için hazırlanmıştır. Ancak bu alanın çok hızlı ilerlemesi nedeniyle bu metni güncel tutmak (ve bir sonraki baskı için gerekirse hazır bulunmak için) metin içeriği burada güncellenecektir.
author:
  - first_name: "Serdar"
    last_name: "Balci"
    url: https://github.com/sbalci
    affiliation: serdarbalci.com
    affiliation_url: https://www.serdarbalci.com
    orcid_id: 0000-0002-7852-3851
# date: "`r Sys.Date()`"
date: 2023-05-19
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r}
htmltools::includeMarkdown(path = 
                             "https://raw.githubusercontent.com/sbalci/patoloji-ve-bilisim/main/README.md"
                             )
```


