---
name: Serdar Balci
position: "Associate Professor of Pathology"
address: "Independent Researcher"
phone: +90 533 4472096
profilepic: SerdarBalci-MD-Pathologist.jpg
www: serdarbalci.com
email: "drserdarbalci@gmail.com"
twitter: serdarbalci
github: sbalci
linkedin: serdar-balci-md-pathologist
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Serdar Balci is a pathologist."
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(RefManageR)
library(vitae)
```

# About Me

* https://about.me/serdarbalci
* I use https://twitter.com/serdarbalci frequently.
* See https://www.serdarbalci.com/ for main web page
* http://www.patolojinotlari.com/ for Turkish Lecture Notes & Social Media Based Notes
* https://sbalci.github.io/MyRCodesForDataAnalysis/ for R codes,
* https://sbalci.github.io/pubmed/BibliographicStudies.html for Bibliographic studies.


<!-- # Education -->

<!-- ```{r education, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE} -->
<!-- edu <- rorcid::orcid_educations("0000-0002-7852-3851") -->
<!-- edu$`0000-0002-7852-3851`$`education-summary` %>% -->
<!--   detailed_entries( -->
<!--     what = `role-title`, -->
<!--     when = glue::glue("{`start-date.year.value`} - {`end-date.year.value`}"), -->
<!--     with = organization.name, -->
<!--     where = organization.address.city -->
<!--   ) -->
<!-- ``` -->



<!-- # Publications -->

<!-- ```{r publications} -->
<!-- scholar::get_publications("q40DcqYAAAAJ") %>%  -->
<!--     vitae::detailed_entries( -->
<!--     what = title, -->
<!--     when = year, -->
<!--     with = author, -->
<!--     where = journal, -->
<!--     why = cites -->
<!--   ) -->
<!-- ``` -->


# Selected talks

```{r talks}
tibble::tribble(
  ~name, ~event, ~location, ~year,
  "Empowering people with community, software, and peer review", "**RUCK: R Users Conference Korea (Invited Keynote speaker)**", "Seoul, Korea", 2018,
  "Now you see it?  Now you don’t?  The role of graphics in identifying MCMC convergence (Awarded Runner up Pitman Prize for Young Statistician)", "ISCB-ASC", "Melbourne, Australia", 2018,
  "Find the best locations for facilities using `maxcovr`", "UseR! 2018", "Brisbane, Australia", 2018
) %>%
  detailed_entries(
    what = name,
    when = year,
    with = event,
    where = location
  )
```


