name: Sync main branch to Bitbucket

on: [push, delete, create]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: zent-contrib/sync-git-branch@v1.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-branch: main
          destination-repo: "git@gitlab.com:sbalci/patholoji-raporlari.git"
          destination-branch: main  


# name: Mirror and run GitLab CI

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Mirror + trigger CI
#       uses: SvanBoxel/gitlab-mirror-and-ci-action@master
#       with:
#         args: "https://gitlab.com/sbalci/pathology-report"
#       env:
#         GITLAB_HOSTNAME: "gitlab.com"
#         GITLAB_USERNAME: "sbalci"
#         GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # // Generate here: https://gitlab.com/profile/personal_access_tokens
#         GITLAB_PROJECT_ID: "36011188" # // https://gitlab.com/<namespace>/<repository>/edit
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # // https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret


#   pushtogitlab:
#     needs: release
#     name: Deploy to GitLab
#     runs-on: ubuntu-latest
#     steps:
#       - uses: zent-contrib/sync-git-branch@v1.0.0
# #      - uses: zent-contrib/git-branch-sync-action@v1
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#         with:
#           source-branch: privpage
#           destination-repo: "git@gitlab.com:sbalci/pathology-report.git"

       
