# copied from https://github.com/etiennebacher/personal_website_distill/blob/master/.github/workflows/main.yml
# https://github.com/rstudio/distill/issues/350

on:
  push:
    branches: master
  workflow_dispatch:
  schedule:
    - cron: '5 20 * * 6'


name: Render & Deploy sbalci.github.io Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        run: |
          options(repos = "https://cran.r-project.org")
          if (!requireNamespace("rmarkdown", quietly = TRUE)) install.packages("rmarkdown", dependencies = TRUE, quiet = TRUE, verbose = FALSE)
          if (!requireNamespace("markdown", quietly = TRUE)) install.packages("markdown", dependencies = TRUE, quiet = TRUE, verbose = FALSE)
          if (!requireNamespace("distill", quietly = TRUE)) install.packages("distill", dependencies = TRUE, quiet = TRUE, verbose = FALSE)
          if (!requireNamespace("pagedown", quietly = TRUE)) install.packages("pagedown", dependencies = TRUE, quiet = TRUE, verbose = FALSE)
          if (!requireNamespace("fs", quietly = TRUE)) install.packages("fs", dependencies = TRUE, quiet = TRUE, verbose = FALSE)
        shell: Rscript {0}

      - name: Update Pages
        run: |
          # source("./R-scripts/add_random_case.R")
          source("./R-scripts/website.R")
        shell: Rscript {0}

      - name: Render Pages
        run: |
          # rmarkdown::render('./patoloji-ders-notlari/index.Rmd')
          rmarkdown::render('./_posts/patolojide-bilisim/patolojide-bilisim.Rmd')
          rmarkdown::render('./Serdar-Balci-MD-Pathologist-CV.Rmd')
        shell: Rscript {0}


      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
      - name: Copy redirects
        run: Rscript -e 'fs::file_copy("404.md", "docs/404.md")'
      - name: "Remove 404.html"
        run: Rscript -e 'fs::file_delete("docs/404.html")'
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
